BATCH_SIZE = 512
MAX_LENGTH=50
SEQUENCE_LENGTH=50
LEARNING_RATE = 0.01
EPOCHS = 50
BIRNN_NAME= "Bi_RNN"
SCC = "Sprase_Categorigical_Crossentropy"
PATH_TRAIN_MODERN = 'data/train.modern.nltktok'
PATH_VALIDATION_MODERN = 'data/valid.modern.nltktok'
PATH_VALIDATION_ORIGINAL = 'data/valid.modern.nltktok'